apiVersion: v1
kind: Pod
metadata:
  name: xdefi-pod
  labels:
    app: xdefiapp

spec:
  containers:
    - image: sunmicrosystem/xdefitask:latest
      name: xdefitaskapp
      ports:
        - containerPort: 80